parameters:
  DependsOn: ''

stages:
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
    - stage:
      displayName: 'Release'
      dependsOn: ${{ parameters.DependsOn }}
      # Build stage must succeed and the repo must be azure-sdk-for-ios
      condition: succeeded()

      jobs:
      - template: ../jobs/archetype-sdk-release.yml
