parameters:
- name: BuildScheme
  type: string
  default: sdk
  
stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        BuildScheme: ${{parameters.BuildScheme}}

  - template: archetype-sdk-release.yml
    parameters:
      DependsOn: Build
