parameters:
- name: BuildScheme
  type: string
  default: sdk
  
stages:
  - stage: Build
    jobs:
    - template: ../jobs/archetype-sdk-client.yml
      parameters:
        BuildScheme: ${{parameters.BuildScheme}}

  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal')) }}:
    - template: archetype-sdk-release.yml
      parameters:
        DependsOn: Build
